<?php

namespace dokuwiki\plugin\struct\test\mock;

class Assignments extends \dokuwiki\plugin\struct\meta\Assignments
{

    /**
     * @param $forcereload
     * @return \dokuwiki\plugin\struct\test\mock\Assignments
     * @noinspection PhpIncompatibleReturnTypeInspection
     */
    public static function getInstance($forcereload = false)
    {
        return parent::getInstance($forcereload); // TODO: Change the autogenerated stub
    }

    public function matchPagePattern($pattern, $page, $pns = null)
    {
        return parent::matchPagePattern($pattern, $page, $pns);
    }

    // resets the internal singleton instance
    public static function reset()
    {
        self::$instance = null;
    }
}
